version: '3.6'
# https://github.com/docker/cli/issues/1293
services:
  oioioi_db:
    image: library/postgres:12.2
    environment:
      POSTGRES_USER: "oioioi"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "oioioi"
    volumes:
      - postgress-data-dev:/var/lib/postgresql/data
    stop_grace_period: 1m
  oioioi_web:
    image: 127.0.0.1:5000/oioioi
    command: ["/sio2/oioioi/oioioi_init.sh", "--dev"]
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - "oioioi_uid=${OIOIOI_UID}"
      extra_hosts:
        - "oioioi_web:127.0.0.1"
    ports:
    # web server
      - "8000:8000"
    # notifications server
    # - "7887:7887"
    volumes:
      - user-uploads:/sio2/deployment/media
    stop_grace_period: 3m
    depends_on:
      - oioioi_db
      - broker
  worker:
    image: 127.0.0.1/oioioi
    command: ["/sio2/oioioi/worker_init.sh"]
    stop_grace_period: 1m
    cap_add:
      - ALL
    depends_on:
      - oioioi_db
  broker:
    image: library/rabbitmq:3.8
    environment:
      RABBITMQ_DEFAULT_USER: oioioi
      RABBITMQ_DEFAULT_PASS: oioioi
    stop_grace_period: 1m
volumes:
  postgress-data-dev:
  user-uploads:
